import { createSlice } from '@reduxjs/toolkit';

const initialState =[
    {
        gamePage:"firstGame",
        area:[
            {
                rows:[
                    {
                        rowID:"0",
                        col:[
                                {
                        
                                    colName:"col1",
                                    content:[]
                                },
                                {
                                    colName:"col2",
                                    content:[]
                                },
                                {
                                    colName:"col3",
                                    content:[]
                                }
                        ]
                    },
                    {
                        rowID:"1",
                        col:[
                                {
                        
                                    colName:"col1",
                                    content:[]
                                },
                                {
                                    colName:"col2",
                                    content:[]
                                },
                                {
                                    colName:"col3",
                                    content:[]
                                }
                        ]
                    },
                     {
                        rowID:"2",
                        col:[
                                {
                        
                                    colName:"col1",
                                    content:[]
                                },
                                {
                                    colName:"col2",
                                    content:[]
                                },
                                {
                                    colName:"col3",
                                    content:[]
                                }
                        ]
                    }
                ]
            }
        ]
    },
    {
        gamePage:"lateGame",
        area:[
            {
                rows:[
                    {
                        rowID:"0",
                        col:[
                                {
                        
                                    colName:"col1",
                                    content:[]
                                },
                                {
                                    colName:"col2",
                                    content:[]
                                },
                                {
                                    colName:"col3",
                                    content:[]
                                }
                        ]
                    },
                    {
                        rowID:"1",
                        col:[
                                {
                        
                                    colName:"col1",
                                    content:[]
                                },
                                {
                                    colName:"col2",
                                    content:[]
                                },
                                {
                                    colName:"col3",
                                    content:[]
                                }
                        ]
                    },
                     {
                        rowID:"2",
                        col:[
                                {
                        
                                    colName:"col1",
                                    content:[]
                                },
                                {
                                    colName:"col2",
                                    content:[]
                                },
                                {
                                    colName:"col3",
                                    content:[]
                                }
                        ]
                    }
                ]
            }
        ]
    },
    {
        gamePage:"Goblins",
        area:[
            {
                rows:[
                    {
                        rowID:"0",
                        col:[
                                {
                        
                                    colName:"col1",
                                    content:[]
                                },
                                {
                                    colName:"col2",
                                    content:[]
                                },
                                {
                                    colName:"col3",
                                    content:[]
                                }
                        ]
                    },
                    {
                        rowID:"1",
                        col:[
                                {
                        
                                    colName:"col1",
                                    content:[]
                                },
                                {
                                    colName:"col2",
                                    content:[]
                                },
                                {
                                    colName:"col3",
                                    content:[]
                                }
                        ]
                    },
                     {
                        rowID:"2",
                        col:[
                                {
                        
                                    colName:"col1",
                                    content:[]
                                },
                                {
                                    colName:"col2",
                                    content:[]
                                },
                                {
                                    colName:"col3",
                                    content:[]
                                }
                        ]
                    }
                ]
            }
        ]
    },
    {
        gamePage:"Evil",
        area:[
            {
                rows:[
                    {
                        rowID:"0",
                        col:[
                                {
                        
                                    colName:"col1",
                                    content:[]
                                },
                                {
                                    colName:"col2",
                                    content:[]
                                },
                                {
                                    colName:"col3",
                                    content:[]
                                }
                        ]
                    },
                    {
                        rowID:"1",
                        col:[
                                {
                        
                                    colName:"col1",
                                    content:[]
                                },
                                {
                                    colName:"col2",
                                    content:[]
                                },
                                {
                                    colName:"col3",
                                    content:[]
                                }
                        ]
                    },
                     {
                        rowID:"2",
                        col:[
                                {
                        
                                    colName:"col1",
                                    content:[]
                                },
                                {
                                    colName:"col2",
                                    content:[]
                                },
                                {
                                    colName:"col3",
                                    content:[]
                                }
                        ]
                    }
                ]
            }
        ]
    }];
                


const tabsSlice = createSlice(
    {
        name: 'tabs',
        initialState,
        reducers:{

        }
    }
);

export default tabsSlice.reducer;